Repository Tleard/RIL-Ressources, pull requests merged in 2021-01, with the labels that each got.

#3 Refactor naming convention on Resource file name
  API/src/Controller/ResourcesController.php
  API/src/DataFixtures/AppFixtures.php
  API/src/Entity/Resource.php
  API/src/Entity/ResourceAsset.php
  API/src/Entity/ResourceCategory.php
  API/src/Entity/ResourceReaction.php
  API/src/Entity/ResourceStatus.php
  API/src/Entity/ResourceType.php
  API/src/Form/ResourceType.php
  API/src/Repository/ResourcesAssetRepository.php
  API/src/Repository/ResourcesCategoryRepository.php
  API/src/Repository/ResourcesReactionRepository.php
  API/src/Repository/ResourcesRepository.php
  API/src/Repository/ResourcesStatusRepository.php
  API/src/Repository/ResourcesTypeRepository.php
  readme.md
Labels: bug, documentation, enhancement

#4 Improvement on crud Resource
  API/src/Controller/ResourcesController.php
  API/src/Controller/UsersController.php
  API/src/DataFixtures/AppFixtures.php
  API/src/Entity/Resource.php
  API/src/Entity/ResourceStatus.php
  API/src/Entity/ResourceType.php
  API/src/Form/ResourcesType.php
  API/src/Form/UsersType.php
  API/src/Repository/ResourcesStatusRepository.php
  API/src/Repository/ResourcesTypeRepository.php
Labels: bug, enhancement

#5 Feature/crud Quick Fix on UserRegistration
  .gitignore
  API/composer.json
  API/composer.lock
  API/config/bundles.php
  API/config/packages/dev/jms_serializer.yaml
  API/config/packages/jms_serializer.yaml
  API/config/packages/prod/jms_serializer.yaml
  API/config/packages/validator.yaml
  API/src/Controller/ResourcesController.php
  API/src/Controller/UsersController.php
  API/src/Entity/Asset.php
  API/src/Entity/Resource.php
  API/src/Entity/ResourceAsset.php
  API/src/Entity/User.php
  API/src/Form/UsersType.php
  API/src/Repository/AssetRepository.php
  API/src/Repository/UserRepository.php
  API/src/Service/FileManager.php
  API/symfony.lock
Labels: bug

#6 Feature/react components base
  .gitignore
  ressource_relationelle/.eslintcache
  ressource_relationelle/package-lock.json
  ressource_relationelle/package.json
  ressource_relationelle/src/App.js
  ressource_relationelle/src/components/Login.css
  ressource_relationelle/src/components/Login.js
  ressource_relationelle/src/components/Register.css
  ressource_relationelle/src/components/Register.js
  ressource_relationelle/src/components/RessourceTest.js
Labels: enhancement

#7 Fix FileManager, GetResource & Add AssetsController
  API/.gitignore
  API/config/packages/sensio_framework_extra.yaml
  API/src/Controller/AssetController.php
  API/src/Controller/ResourcesAssetController.php
  API/src/Controller/ResourcesController.php
  API/src/Controller/UsersController.php
  API/src/DataFixtures/AppFixtures.php
  API/src/Entity/Asset.php
  API/src/Entity/Resource.php
  API/src/Service/FileManager.php
Labels: bug, enhancement

#8 Fix User routes and CRUD added to User
  API/src/Controller/ResourcesController.php
  API/src/Controller/UsersController.php
  API/src/Entity/User.php
  API/src/Form/UsersPatchType.php
  API/src/Service/FileManager.php
Labels: bug, enhancement

#10 Add: Init React native project, log-in Page
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/app.json
  ressource_relationelle_mobile/assets/PikPng.com_twitter-icons-png_2837538.png
  ressource_relationelle_mobile/assets/adaptive-icon.png
  ressource_relationelle_mobile/assets/favicon.png
  ressource_relationelle_mobile/assets/icon.png
  ressource_relationelle_mobile/assets/logo.png
  ressource_relationelle_mobile/assets/splash.png
  ressource_relationelle_mobile/babel.config.js
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/login.js
Labels: enhancement

#11 Fix RegisterAction
  API/src/Controller/UsersController.php
Labels: bug

#12 Feature/register form
  .gitignore
  ressource_relationelle/.eslintcache
  ressource_relationelle/package-lock.json
  ressource_relationelle/package.json
  ressource_relationelle/src/App.js
  ressource_relationelle/src/ProtectedRoute.js
  ressource_relationelle/src/auth.js
  ressource_relationelle/src/components/Login.js
  ressource_relationelle/src/components/Navigation.js
  ressource_relationelle/src/components/Register.js
  ressource_relationelle/src/components/RessourceTest.js
  ressource_relationelle/src/global.js
  ressource_relationelle/src/index.js
Labels: bug, enhancement, help wanted

#13 ReasourceReactions Crud
  API/src/Controller/ResourcesReactionController.php
  API/src/DataFixtures/AppFixtures.php
  API/src/Entity/Resource.php
  API/src/Entity/ResourceReaction.php
  API/src/Form/ReactionType.php
  API/src/Repository/ResourcesReactionRepository.php
  API/src/Repository/ResourcesRepository.php
  API/src/Repository/UserRepository.php
Labels: enhancement

#14 Feature/mailer
  API/.env_example
  API/.gitignore
  API/composer.json
  API/composer.lock
  API/config/bundles.php
  API/config/config_dev.yml
  API/config/packages/dev/swiftmailer.yaml
  API/config/packages/swiftmailer.yaml
  API/config/packages/test/swiftmailer.yaml
  API/config/parameters.yml
  API/config/services.yaml
  API/migrations/Version20210110154625.php
  API/migrations/Version20210110154727.php
  API/src/Controller/PageController.php
  API/src/Controller/UsersController.php
  API/src/Entity/User.php
  API/symfony.lock
Labels: enhancement

#15 Feature/category crud
  .gitignore
  API/src/Controller/ResourcesCategoryController.php
  API/src/Entity/ResourceCategory.php
Labels: enhancement

#16 FIx Crud Delete category
  API/src/Controller/ResourcesCategoryController.php
  API/src/Entity/ResourceCategory.php
Labels: enhancement

#17 Feature/mobile request setup
  .gitignore
  ressource_relationelle_mobile/API/LoginAttempt.js
  ressource_relationelle_mobile/API/RequestHandler.js
  ressource_relationelle_mobile/API/TokenHandler.js
  ressource_relationelle_mobile/API/UserHandler.js
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/screens/logInScreen.js
  ressource_relationelle_mobile/screens/login.js
Labels: enhancement

#18 Add user to Json response on login
  API/src/Controller/UsersController.php
Labels: bug, enhancement

#19 Improve RequestHandler system
  ressource_relationelle_mobile/API/LoginAttempt.js
  ressource_relationelle_mobile/API/TokenHandler.js
  ressource_relationelle_mobile/API/UserHandler.js
  ressource_relationelle_mobile/screens/logInScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#20 Add: Register and Loader
  ressource_relationelle_mobile/.gitignore
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/assets/Success-PNG-Image.png
  ressource_relationelle_mobile/screens/Components/Loader.js
  ressource_relationelle_mobile/screens/RegisterScreen.js
Labels: enhancement

#23 Feature/mobile request setup
  API/src/Controller/AssetController.php
  API/src/Controller/ResourcesController.php
  API/src/DataFixtures/AppFixtures.php
  API/src/Entity/Asset.php
  API/src/Entity/ResourceCategory.php
  API/src/Entity/ResourceStatus.php
  API/src/Entity/User.php
  API/src/Service/FileManager.php
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/screens/logInScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: enhancement

#24 Small Fix User remove double
  API/src/Entity/User.php
Labels: bug
