Repository Tleard/RIL-Ressources, pull requests merged in 2021-02, with the labels that each got.

#26 Register validation fixed
  ressource_relationelle/.eslintcache
  ressource_relationelle/src/components/Login.js
  ressource_relationelle/src/components/Register.js
Labels: enhancement

#27 fix display of one resource + add report icon
  ressource_relationelle/.eslintcache
  ressource_relationelle/src/components/Categories.js
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Resource.js
  ressource_relationelle/src/components/ResourceCardDetail.css
  ressource_relationelle/src/components/ResourceCardDetail.js
Labels: enhancement

#28 Material Rework for React Native
  API/src/Controller/UsersController.php
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/RegisterScreen.js
  ressource_relationelle_mobile/screens/logInScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#29 Feature/home page
  ressource_relationelle/.eslintcache
  ressource_relationelle/package-lock.json
  ressource_relationelle/package.json
  ressource_relationelle/src/components/Home.js
  ressource_relationelle/src/components/HomeCarousel.js
Labels: enhancement

#32 Fix/route url path
  ressource_relationelle/package-lock.json
  ressource_relationelle/package.json
  ressource_relationelle/src/App.js
  ressource_relationelle/src/components/Categories.js
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Home.js
Labels: enhancement

#33 Draft Profile for User
  API/src/Controller/ResourcesReactionController.php
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/assets/default-picture.png
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#34 CustomSideBar
  ressource_relationelle_mobile/screens/Components/CustomSidebarMenu.js
Labels: enhancement

#35 Screen for all ressources
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/screens/AllResourcesScreen.js
  ressource_relationelle_mobile/screens/RegisterScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: enhancement

#38 Add Acces & Function to single ressource view on Profile
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
  ressource_relationelle_mobile/screens/ResourceDetailsScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: enhancement

#42 Refactor/refactor librairy
  API/src/Controller/LibrariesController.php
  API/src/Controller/ResourcesController.php
  API/src/Controller/UsersController.php
Labels: enhancement

#43 Fix Annotation + Resource name
  API/src/Controller/LibrariesController.php
Labels: enhancement

#44 Switch back UserController before Refactor
  API/src/Controller/UsersController.php
Labels: enhancement

#45 Reworked CSS
  ressource_relationelle/src/App.css
  ressource_relationelle/src/App.js
  ressource_relationelle/src/components/Home.js
  ressource_relationelle/src/components/Login.js
  ressource_relationelle/src/components/Navigation.js
  ressource_relationelle/src/components/Publication.js
  ressource_relationelle/src/components/Resource.js
Labels: enhancement

#46 Feature/mobile single resource
  API/src/Controller/ResourcesController.php
  API/src/Service/FileManager.php
  ressource_relationelle/src/components/Home.js
  ressource_relationelle_mobile/API/LoginAttempt.js
  ressource_relationelle_mobile/screens/ResourceDetailsScreen.js
  ressource_relationelle_mobile/screens/logInScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#47 CreateResource, CategoryScreen, CategoryItems Screen
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/CategoryResourcesScreen.js
  ressource_relationelle_mobile/screens/CategoryScreen.js
  ressource_relationelle_mobile/screens/Components/CategoryItem.js
  ressource_relationelle_mobile/screens/CreateResourceScreen.js
Labels: enhancement

#48 Add Ressource in library fully working
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Resource.js
  ressource_relationelle/src/components/UserLibrary.js
Labels: bug, enhancement

#49 Fix/create reaction merge to ongoing change
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Resource.js
  ressource_relationelle/src/components/UserLibrary.js
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
Labels: enhancement

#51 Feature add reaction is working
  API/src/Entity/ResourceReaction.php
  ressource_relationelle/src/auth.js
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Login.js
  ressource_relationelle/src/components/Resource.js
  ressource_relationelle/src/userLibraryFunctions.js
Labels: enhancement

#52 Feature report resource and user + fixes
  API/src/Controller/UsersController.php
  ressource_relationelle/public/images/logo_main.jpg
  ressource_relationelle/public/images/logo_meeting.jpg
  ressource_relationelle/public/images/logo_pc.jpg
  ressource_relationelle/public/images/logo_postit.jpg
  ressource_relationelle/public/images/main.jpg
  ressource_relationelle/public/images/pc.jpg
  ressource_relationelle/public/images/postit.jpg
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/Home.js
  ressource_relationelle/src/components/HomeCarousel.js
  ressource_relationelle/src/components/NavDrawer.js
  ressource_relationelle/src/components/Navigation.js
  ressource_relationelle/src/components/Publication.js
  ressource_relationelle/src/components/Resource.js
  ressource_relationelle/src/components/UserLibrary.js
  ressource_relationelle/src/userLibraryFunctions.js
Labels: bug, enhancement

#53 Requested Validation before push on createResources
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/screens/AllResourcesScreen.js
  ressource_relationelle_mobile/screens/CategoryResourcesScreen.js
  ressource_relationelle_mobile/screens/CategoryScreen.js
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
  ressource_relationelle_mobile/screens/CreateResourceScreen.js
  ressource_relationelle_mobile/screens/ResourceDetailsScreen.js
Labels: bug, enhancement

#54 Fix/mobile refresh
  API/src/DataFixtures/AppFixtures.php
  ressource_relationelle_mobile/App.js
  ressource_relationelle_mobile/package-lock.json
  ressource_relationelle_mobile/package.json
  ressource_relationelle_mobile/screens/AllResourcesScreen.js
  ressource_relationelle_mobile/screens/CategoryScreen.js
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
  ressource_relationelle_mobile/screens/FavoriteScreen.js
  ressource_relationelle_mobile/screens/ResourceDetailsScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#56 Fix the state
  ressource_relationelle/src/components/Category.js
Labels: bug, enhancement

#57 Add feature see profile user
  ressource_relationelle/src/App.js
  ressource_relationelle/src/components/Category.js
  ressource_relationelle/src/components/NavDrawer.js
  ressource_relationelle/src/components/Navigation.js
  ressource_relationelle/src/components/Profile.js
  ressource_relationelle/src/components/Resource.js
Labels: enhancement

#58 Fix/mobile refresh
  API/setup.md
  ressource_relationelle_mobile/screens/Components/ResourceItem.js
  ressource_relationelle_mobile/screens/CreateResourceScreen.js
  ressource_relationelle_mobile/screens/ResourceDetailsScreen.js
  ressource_relationelle_mobile/screens/profileScreen.js
Labels: bug, enhancement

#59 Minor fixes for Library and register
  ressource_relationelle/src/components/UserLibrary.js
  ressource_relationelle_mobile/screens/RegisterScreen.js
Labels: bug
